BasketballProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basketballapp430.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

basketballapp430/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.loginView, name = 'login'),
    path('logout/', views.logoutView, name = 'logout'),
    path('register/', views.registerView, name = 'register'),
    path('', views.home, name = 'home'),
    path('playerstats/', views.playerstats, name = 'playerstats'),
    path('playerstats/addplayer/', views.addPlayer, name = 'addplayer'),
    path('playerstats/updateplayer/<str:pk>/', views.updatePlayer, name = 'updatePlayer'),
    path('playerstats/deleteplayer/<str:pk>/', views.deletePlayer, name = 'delete-player'),
    path('playerstats/playerprofile/<str:pk>/', views.playerProfile, name = 'player-profile'),
    path('article/', views.article_list, name = 'article'),
    path('article/addarticle', views.addArticle, name = 'add-article'),
    path('article/updatearticle/<str:pk>/', views.updatearticle, name = 'update-article'),
    path('article/deletearticle/<str:pk>/', views.deletearticle, name = 'delete-article'),


]

basketballapp430/models.py
from django.db import models
from django_countries.fields import CountryField
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

# Create your models here.

class Player(models.Model):


    POINTGUARD = 'PG'
    SHOOTINGGUARD = 'SG'
    SMALLFORWARD = 'SF'
    POWERFORWARD = 'PF'
    CENTER = 'C'

    POSITION_CHOICES = [
        (POINTGUARD, 'Point Guard'),
        (SHOOTINGGUARD, 'Shooting Guard'),
        (SMALLFORWARD, 'Small Forward'),
        (POWERFORWARD, 'Power Forward'),
        (CENTER, 'Center')
        
    ]

    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=255, default = '')
    phone = models.CharField(max_length=20)
    age = models.IntegerField()
    nationality = CountryField()
    position = models.CharField(max_length=2, choices=POSITION_CHOICES)
    games_played = models.IntegerField(default=0)
    points_per_game = models.FloatField(default=0)
    rebounds_per_game = models.FloatField(default=0)
    assists_per_game = models.FloatField(default=0)
    steals_per_game = models.FloatField(default=0)
    blocks_per_game = models.FloatField(default=0)
    fieldgoals_per_game = models.FloatField(default=0)
    three_point_field_goal_percentage = models.FloatField(default=0)
    free_throw_percentage = models.FloatField(default=0)

    def __str__(self):
        return self.name
    
    def data_score(self):
        
        stats = {
            'points_per_game': {
                (0,2): 0,
                (2,5): 0.2,
                (5,8): 0.3,
                (8,12): 0.45,
                (12,16): 0.55,
                (16,20): 0.8,
                (20,25): 0.9,
                (25,float('inf')): 1
            },
            'rebounds_per_game':{
                (0,4):0,
                (4,6):0.3,
                (6,8):0.5,
                (8,11):0.75,
                (11,13):0.95,
                (13,float('inf')):1
            },
            'assists_per_game':{
                (0,2):0,
                (2,4):0.6,
                (4,6):1,
                (6,8):1.4,
                (8,10):1.7,
                (10,12):1.95,
                (12,float('inf')):2
            },
            'steals_per_game':{
                (0,1):0,
                (1,2):0.2,
                (2,4):0.5,
                (4,6):0.8,
                (6,9):0.95,
                (9,float('inf')):1
            },
            'blocks_per_game':{
                (0,1):0,
                (1,2):0.4,
                (2,4):0.6,
                (4,7):0.85,
                (7,10):0.95,
                (10,float('inf')):1
            },
            'fieldgoals_per_game':{
                (0,1): 0,
                (1,3): 0.1,
                (3,5): 0.25,
                (5,7): 0.5,
                (7,10): 0.75,
                (10,15): 0.9,
                (15,20): 0.95,
                (20,float('inf')): 1
            },
            'three_point_field_goal_percentage':{
                (0,10):0,
                (10,15):0.1,
                (15,20):0.2,
                (20,25):0.3,
                (25,30):0.4,
                (30,35):0.55,
                (35,45):0.65,
                (45,55):0.75,
                (55,70):0.85,
                (70,85):0.95,
                (85,100):1
            },
            'free_throw_percentage':{
                (0,30):0,
                (30,40):0.1,
                (40,50):0.2,
                (50,60):0.35,
                (60,70):0.5,
                (70,80):0.75,
                (80,90):0.9,
                (90,95):0.95,
                (95,100):1
            }
        }

        score = 0
        for stat, ranges in stats.items():
            stat_value = getattr(self, stat)
            for r in ranges:
                if r[0] <= stat_value <= r[1]:
                    score+=ranges[r]
                    break
        return score


class Article(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateTimeField(default='01-01-2000 00:00:00')
    description = models.TextField(null=True)

    def __str__(self):
        return self.title



    

basketballapp430/forms.py
from django.forms import ModelForm
from django import forms

from .models import Player, Article

class PlayerForm(ModelForm):
    class Meta:
        model = Player
        fields = '__all__'
    three_point_field_goal_percentage = forms.FloatField(min_value=0.0, max_value=100.0)
    free_throw_percentage = forms.FloatField(min_value=0.0, max_value=100.0)
    

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = '__all__'
    date = forms.DateTimeField(input_formats=['%d-%m-%Y %H:%M:%S'])
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 5}))
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].initial = '01-01-2000 00:00:00'

class StatFilter(forms.Form):
    STAT_CHOICE = [('', 'Any'),('points_per_game', 'Point/game'),('rebounds_per_game', 'Rebounds/game'),('assists_per_game', 'Assists/game'),
    ('steals_per_game', 'Steals/game'),(' blocks_per_game', 'Blocks/game'),('fieldgoals_per_game', 'FG/game'),('three_point_field_goal_percentage', '3P%'),('free_throw_percentage', 'FT%')
    ]
    stat = forms.ChoiceField(choices=STAT_CHOICE, required=False)

basketballapp430/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .models import Player, Article
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .forms import PlayerForm, ArticleForm, StatFilter

# Create your views here.


@login_required(login_url='login')
def home(request):
    return render(request, 'home.html', {'name': request.user})

def loginView(request):

    page = 'login'

    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, "User does not exist")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, "Incorrect username or password")

    context = {'page': page}
    return render(request, 'login.html', context)

def registerView(request):
    form = UserCreationForm()   

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, "Error during registration")


    context = {'form': form}
    return render(request, 'login.html', context)


@login_required(login_url='login')
def logoutView(request):
    logout(request)
    return redirect('login')


@login_required(login_url='login')
def playerstats(request):
    form = StatFilter(request.GET)
    if form.is_valid():
        stat = form.cleaned_data['stat']
        if stat == '':
            players = Player.objects.all().order_by('name')
        elif stat:
            players = Player.objects.all().order_by('-{}'.format(stat))
        else:
            players = Player.objects.all().order_by('name')
    else:
        players = Player.objects.all().order_by('name')
    return render(request, 'playerstats.html', {'form': form, 'players': players})

@login_required(login_url='login')
def addPlayer(request):
    form = PlayerForm()
    if request.method == 'POST':
        form = PlayerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('playerstats')


    context = {'form': form}
    return render(request, 'addplayer.html', context)


@login_required(login_url='login')
def updatePlayer(request, pk):
    player = Player.objects.get(id=pk)
    form = PlayerForm(instance = player)

    if request.method == 'POST':
        form = PlayerForm(request.POST, instance=player)
        if form.is_valid():
            form.save()
            return redirect('playerstats')



    context = {'form': form}
    return render(request, 'addplayer.html', context)

@login_required(login_url='login')
def deletePlayer(request, pk):
    player = Player.objects.get(id=pk)
    if request.method == 'POST':
        player.delete()
        return redirect('playerstats')
    context = {'player': player}
    return render(request, 'deleteplayer.html', context)

@login_required(login_url='login')
def playerProfile(request, pk):
    player = Player.objects.get(id=pk)
    context = {'player': player}
    return render(request, 'playerprofile.html', context)

@login_required(login_url='login')
def article_list(request):
    articles_list = Article.objects.all()
    return render(request, 'article_list.html',{"articles" : articles_list})

@login_required(login_url='login')
def addArticle(request):
    form = ArticleForm()
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('article')


    context = {'form': form}
    return render(request, 'addarticle.html', context)

@login_required(login_url='login')
def updatearticle(request, pk):
    article = Article.objects.get(id=pk)
    form = ArticleForm(instance = article)

    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('article')



    context = {'form': form}
    return render(request, 'addarticle.html', context)

@login_required(login_url='login')
def deletearticle(request, pk):
    article = Article.objects.get(id=pk)
    if request.method == 'POST':
        article.delete()
        return redirect('article')
    context = {'article': article}
    return render(request, 'deletearticle.html', context) 

basketballapp430/templates/addarticle.html
{% extends "main.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Add to schedule"/>

    </form>
</div>
{% endblock %}

basketballapp430/templates/addplayer.html
{% extends "main.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Add to database"/>

    </form>
</div>
{% endblock %}

basketballapp430/templates/article_list.html
{% extends "main.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<head>
    <meta charset="utf-8">
    <title>Schedule</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #F7F7F7;
        }
        
        h1 {
            color: #444444;
            text-align: center;
        }
        
        .article {
            background-color: #FFFFFF;
            border: 1px solid #DDDDDD;
            border-radius: 5px;
            padding: 10px;
            margin-bottom: 10px;
            position: relative;
        }
        
        .article h2 {
            color: #333333;
            font-size: 18px;
            margin-bottom: 5px;
        }
        
        .article p {
            color: #666666;
            font-size: 14px;
            margin-bottom: 5px;
        }
        
        .article .date {
            font-size: 12px;
            color: #999999;
            margin-bottom: 10px;
        }
        
        .article .actions {
            position: absolute;
            top: 5px;
            right: 5px;
            font-size: 12px;
        }
        
        .article .actions a {
            color: #0077CC;
            text-decoration: none;
            margin-left: 5px;
        }
        
        .article .actions a:hover {
            text-decoration: underline;
        }
        
        .add-link {
            text-align: center;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <h1>Schedule</h1>
    {% for art in articles %}
        <div class="article">
            <h2>{{ art.title }}</h2>
            <p>{{ art.description }}</p>
            <div class="date">{{ art.date }}</div>
            <div class="actions">
                <a href = "{% url 'update-article' art.id%}">Update</a>
                <a href = "{% url 'delete-article' art.id%}">Delete</a>
            </div>
        </div>
    {% endfor %}
    <div class="add-link">
        <a href="{% url 'add-article' %}">Add new item to the schedule</a>
    </div>
</body>
{% endblock %}

basketballapp430/templates/deletearticle.html
{% extends "main.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="popup">
    <h2>Are you sure you want to delete article {{article.title}} from the schedule?</h2>
    <p>This action cannot be undone.</p>
        <form method="POST" action="">
            {% csrf_token %}
            <!-- your form inputs here -->
            
            <button id="cancel-btn" type="button"><a href="{{ request.META.HTTP_REFERER }}">Cancel</a></button>
            <button id="confirm-btn" type="submit">Confirm</button>
          </form>
  </div>
  
  <!-- Add this to your CSS file -->
  <style>
    .popup {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      background-color: white;
      border: 1px solid #ccc;
      padding: 20px;
      z-index: 9999;
      text-align: center;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
    }
  
    .popup h2 {
      margin-top: 0;
    }
  
    .popup-buttons {
      margin-top: 20px;
    }
  
    .popup-buttons button {
      padding: 10px 20px;
      border: 1px solid #ccc;
      background-color: #f2f2f2;
      margin-right: 10px;
      cursor: pointer;
    }
  
    .popup-buttons button:hover {
      background-color: #ccc;
    }
  </style>
  
  <!-- Add this to your JavaScript file -->
  <script>
    const popup = document.querySelector('.popup');
    const cancelBtn = document.querySelector('#cancel-btn');
    const confirmBtn = document.querySelector('#confirm-btn');
  
    cancelBtn.addEventListener('click', () => {
      popup.style.display = 'none';
    });
  
    confirmBtn.addEventListener('click', () => {
      // Add your confirm action here
      popup.style.display = 'none';
    });
  </script>
{% endblock %}

basketballapp430/templates/deleteplayer.html
{% extends "main.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="popup">
    <h2>Are you sure you want to delete {{player.name}} from the database?</h2>
    <p>This action cannot be undone.</p>
        <form method="POST" action="">
            {% csrf_token %}
            <!-- your form inputs here -->
            
            <button id="cancel-btn" type="button"><a href="{{ request.META.HTTP_REFERER }}">Cancel</a></button>
            <button id="confirm-btn" type="submit">Confirm</button>
          </form>
  </div>
  
  <!-- Add this to your CSS file -->
  <style>
    .popup {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      background-color: white;
      border: 1px solid #ccc;
      padding: 20px;
      z-index: 9999;
      text-align: center;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
    }
  
    .popup h2 {
      margin-top: 0;
    }
  
    .popup-buttons {
      margin-top: 20px;
    }
  
    .popup-buttons button {
      padding: 10px 20px;
      border: 1px solid #ccc;
      background-color: #f2f2f2;
      margin-right: 10px;
      cursor: pointer;
    }
  
    .popup-buttons button:hover {
      background-color: #ccc;
    }
  </style>
  
  <!-- Add this to your JavaScript file -->
  <script>
    const popup = document.querySelector('.popup');
    const cancelBtn = document.querySelector('#cancel-btn');
    const confirmBtn = document.querySelector('#confirm-btn');
  
    cancelBtn.addEventListener('click', () => {
      popup.style.display = 'none';
    });
  
    confirmBtn.addEventListener('click', () => {
      // Add your confirm action here
      popup.style.display = 'none';
    });
  </script>
{% endblock %}

basketballapp430/templates/home.html
{% extends "main.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1> Welcome to your home page, {{name}}</h1>
<a href = "playerstats/">Click to see player stats</a>
<br></br>
<a href = "{% url 'article' %}">Click to see upcoming schedule</a>

{% endblock %}

basketballapp430/templates/login.html
{% extends "main.html" %}

{% block title %}Home{% endblock %}

{% block content %}
  <div class="container">
    {% if page == "login" %}
      <div class="card">
        <style>
            .card-body {
              width: 400px;
              margin: 0 auto;
            }
          </style>
        <h2 class="card-header">Login</h2>
        <div class="card-body" style="max-width: 500px; margin: 0 auto;">
          <form method="POST" action="">
            {% csrf_token %}
            <div class="form-group">
              <label for="username">Username:</label>
              <input type="text" class="form-control" id="username" name="username" placeholder="Enter username" required>
            </div>
            <div class="form-group">
              <label for="password">Password:</label>
              <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" required>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
          </form>
          <div class="card-footer">
            <p class="text-muted">Don't have an account?</p>
            <a href="{% url 'register' %}" class="btn btn-outline-primary">Sign up</a>
          </div>
        </div>
      </div>
    {% else %}
      <div class="card">
        <style>
            .card-body {
              width: 900px;
              margin: 0 auto;
            }
          </style>
        <h2 class="card-header">Sign up</h2>
        <div class="card-body" style="max-width: 500px; margin: 0 auto;">
          <form method="POST" action="">
            {% csrf_token %}
            <div>
              {{form.as_p}}
            </div>
            <button type="submit" class="btn btn-primary">Sign up</button>
          </form>
          <div class="card-footer">
            <p class="text-muted">Already have an account?</p>
            <a href="{% url 'login' %}" class="btn btn-outline-primary">Log in</a>
          </div>
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

basketballapp430/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}My Basketball App{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <style>
      /* Your custom styles here */
    </style>
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">
        <img src="/static/images/basketballogo.jpg" alt="Basketball Logo" height="100 px">
        Basketball App
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            {% if request.user.is_authenticated%}
            <a class="nav-link" href= "{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-link" href= "{% url 'login' %}">Login</a>
            {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Link 2</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Link 3</a>
          </li>
        </ul>
      </div>
    </nav>

    <!-- Main Content -->
    <main role="main" class="container my-4">
      {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
      {% block content %}
      {% endblock %}
    </main>

    <!-- Footer -->
    <footer class="bg-light py-3">
      <div class="container text-center">
        <p>&copy; 2023 My Basketball App</p>
        <p>Powered by Django</p>
      </div>
    </footer>

    <!-- Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.3/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

basketballapp430/templates/playerprofile.html
{% extends "main.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<head>
	<title>{{ player.name }}'s Profile</title>
</head>
<body>
	<h1>{{ player.name }}'s Profile</h1>
	<h2>Personal Info</h2>
	<ul>
		<li>Email: {{ player.email }}</li>
		<li>Phone: {{ player.phone }}</li>
		<li>Age: {{ player.age }}</li>
		<li>Nationality: {{ player.nationality }}</li>
		<li>Position: {{ player.get_position_display }}</li>
	</ul>
	<h2>Stats</h2>
	<ul>
		<li>Games Played: {{ player.games_played }}</li>
		<li>Points Per Game: {{ player.points_per_game }}</li>
		<li>Rebounds Per Game: {{ player.rebounds_per_game }}</li>
		<li>Assists Per Game: {{ player.assists_per_game }}</li>
		<li>Steals Per Game: {{ player.steals_per_game }}</li>
		<li>Blocks Per Game: {{ player.blocks_per_game }}</li>
		<li>Field Goals Per Game: {{ player.fieldgoals_per_game }}</li>
		<li>Three Point Field Goal Percentage: {{ player.three_point_field_goal_percentage }}</li>
		<li>Free Throw Percentage: {{ player.free_throw_percentage }}</li>
	</ul>
</body>
{% endblock %}

basketballapp430/templates/playerstats.html
{% extends "main.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<style>
  table {
    border-collapse: collapse;
    width: 100%;
  }
  
  th, td {
    border: 1px solid #ddd;
    padding: 8px;
    text-align: left;
  }
  
  th {
    background-color: #f2f2f2;
  }
</style>

<form method="get">
  {{ form.as_p }}
  <button type="submit">Sort</button>
  <br></br>
</form>
      <table>
          <tr>
              <th>Player ID</th>
              <th>Name</th>
              <th>Email</th>
              <th>Phone number</th>
              <th>Age</th>
              <th>Nationality</th>
              <th>Position</th>
              <th>Games played</th>
              <th>PPG</th>
              <th>RPG</th>
              <th>APG</th>
              <th>SPG</th>
              <th>BPG</th>
              <th>FG PG</th>
              <th>3P%</th>
              <th>FT%</th>
              <th>Data-driven score /10</th>

              
          </tr>
          {% for player in players %}                         
          <tr> 
              <td>{{ player.id }}</td>
              <td><a href = "{% url 'player-profile' player.id %}">{{ player.name }}</a></td>
              <td>{{ player.email }}</td>
              <td>{{ player.phone }}</td>
              <td>{{ player.age }}</td>
              <td>{{ player.nationality }}</td>
              <td>{{ player.position }}</td>
              <td>{{ player.games_played }}</td>
              <td>{{ player.points_per_game }}</td>
              <td>{{ player.rebounds_per_game }}</td>
              <td>{{ player.assists_per_game }}</td>
              <td>{{ player.steals_per_game }}</td>
              <td>{{ player.blocks_per_game }}</td>
              <td>{{ player.fieldgoals_per_game }}</td>
              <td>{{ player.three_point_field_goal_percentage }}</td>
              <td>{{ player.free_throw_percentage }}</td>
              <td>{{ player.data_score}}</td>
              <td><a href = "{% url 'updatePlayer' player.id       %}">Edit player information</a></td>
              <td><a href = "{% url 'delete-player' player.id       %}">Delete player</a></td>

          </tr>
          {% endfor %}
      </table>
      <br></br>
      <div>
        <a href = 'addplayer/'> Add a new player to the database</a>
      </div>

{% endblock %}





  